### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by andrewmcgivery** [andrewmcgivery/obsidian-soundscapes#13]
# Up Next

Next on the roadmap for this plugin is "My Music". This functionality will allow you to play local music files (E.g. MP3s) instead of playing music from YouTube and will include a dedicated interface for viewing, searching, and managing your music library while also allowing you to utilize the mini-player (status bar) to play, pause, control volume, and go next/previous from anywhere within Obsidian.

This is currently a work in progress and I'll be looking to beta test this before it goes live but here's a screenshot of the (functional!) prototype to give you an idea:

![image](https://github.com/andrewmcgivery/obsidian-soundscapes/assets/4482878/7e5c9979-4737-4353-a240-a847a50ef0e7)

More updates will be poste in #5 

# Backlog

The following are not commitments but rather things to explore and potentially make into features:

- My Music Enhancements (Playlists, metadata updates, etc)
- Spotify integration
- Mobile Support

**Comment by phthallo** [comment]
Would definitely be open to beta-test new features :) (also - nice, Anberlin)

**Comment by ThomasEricB** [comment]
With @phthallo. If you need someone to beta test, just tag me :)
