### ISSUE TITLE
[Bug] Using Obsidian-Soundscapes with obsidian-statusbar-organizer completely breaks the status bar

### ISSUE THREAD

**Issue by ThomasEricB** [andrewmcgivery/obsidian-soundscapes#21]
Basically the title. Using Obsidian-Soundscapes with obsidian-statusbar-organizer completely breaks the status bar. It starts spawning multiple instances of Soundscapes and it completely breaks the plugin.

![Obsidian_ICa72BMmmN](https://github.com/andrewmcgivery/obsidian-soundscapes/assets/9662095/f450a53c-6a52-462c-a600-32beecefe4b6)

![Obsidian_3EaPCR5v0x](https://github.com/andrewmcgivery/obsidian-soundscapes/assets/9662095/bbdf4e78-9feb-4ef5-bd95-0fc0dd7b1838)

**Comment by ThomasEricB** [comment]
I also made this an issue at https://github.com/Opisek/obsidian-statusbar-organizer/issues/2

**Comment by Opisek** [comment]
Here's what happens:
- My plugin saves a reference to you music player.
- My plugin removes everything from the status bar.
- My plugin adds everything back by the saved references.

It looks to me like your plugin logic is strictly embedded in the status bar element itself.
E.g. The music completely stops playing when the element is gone, so it's not just a visualization.

Now, when my plugin adds your music player back, it reacts as if it had just been initialized, so it adds all the HTML components once more.

Currently I don't see how I could fix it on my end. Would it be possible to separate the your plugin's logic from the status bar UI?

**Comment by Opisek** [comment]
Good news @ThomasEricB 

Turns out my time estimate to make the two plugins work together on my side was way off.
I've resolved the issue [here](https://github.com/Opisek/obsidian-statusbar-organizer/pull/3). Just update my plugin in Obsidian to 1.3.0.

As such, I've handled the compatibility on my side, so the issue can be closed.

**Comment by andrewmcgivery** [comment]
Thank you @Opisek for jumping on this quickly!

Out of curiosity, what ended up being the fix? Isn't jumping out to me in your PR what specifically fixed the compatibility. :)

**Comment by ThomasEricB** [comment]
Thanks to @Opisek and @andrewmcgivery for being really responsive on this. You guys rock ❤️
