### ISSUE TITLE
Ability to sort/play "My music" by subfolder

### ISSUE THREAD

**Issue by just-a-garlic-bread** [andrewmcgivery/obsidian-soundscapes#22]
Since the plugin only has  the ability to add only one main "music" playlist, it would be nice to have an ability to play music by subfolders, instead of just flattening the music to one single list.Maybe it could be done in a way similar to the obsidian file tree, or just using obsidian's right click menu on an actual obsidian file tree menu?

(May be a duplicate request, since i saw there's already a request for search by tags, but tags and folders are quite different in my opinion)
(Also, i thank you really much for your work, the plugin is absolutely awesome)

**Comment by andrewmcgivery** [comment]
Closing in favor of #27 :)
