### ISSUE TITLE
Nightride FM soundscape

### ISSUE THREAD

**Issue by ChadJeffreyAnderson** [andrewmcgivery/obsidian-soundscapes#24]
I've already added it to my own install (thank you for the custom feature!), but I think **Nightride FM** would make a great addition to the built-in repertoire. They have different flavors of synthwave spread over four YouTube livestreams, which translates nicely to a Soundscape comprised of four tracks.

- **Nightride FM**: https://www.youtube.com/watch?v=uYfxDF_QR94
- **ChillSynth FM**: https://www.youtube.com/watch?v=UedTcufyrHc
- **Datawave FM**: https://www.youtube.com/watch?v=Y9q6RYg2Pdg
- **Spacesynth FM**: https://www.youtube.com/watch?v=5-anTj1QrWs

**Comment by andrewmcgivery** [comment]
ChillSynth has been added to settings in 1.3.0 (just released). :)
