### ISSUE TITLE
Feature Request: cache frequently-used sounds

### ISSUE THREAD

**Issue by SongshGeo** [andrewmcgivery/obsidian-soundscapes#3]
Hi there. 
Obsidian-soundscapes is my daily used plugin now. Thanks for your efforts on this. 

However, I travel a lot and need help to use the soundscape when doing offline jobs during a trip. 
It would be much better when it can cache frequently used sounds automatically.

Best wishes.

**Comment by andrewmcgivery** [comment]
Thank you for opening an issue! :) Love hearing that you're enjoying the plugin!

So, the plugin currently uses YouTube to play the soundscapes. Unfortunately, YouTube doesn't allow for offline play without a YouTube Premium plan and even with that, it's APIs don't allow for me to take advantage of that. They only support offline play through their official apps.

I looked around to see if there was any workarounds but everything I found would be against their terms, and therefore illegal.

So at this point in time, this is unfortunately not possible. :(

**Comment by SongshGeo** [comment]
Thanks for the efforts. I'll keep an eye on any available source, too. :)

**Comment by andrewmcgivery** [comment]
@SongshGeo Currently working on prototyping for local music files.

It's not quite the same as using the soundscapes in offline mode buuuut you will be able to use your local music files offline.

Just a heads up incase you're interested in that when that drops. :)

**Comment by SongshGeo** [comment]
Sounds Great. I listened to local sounds within an addon page in the side pane. However, it turns off whenever I collapse the side pane. That's why I turned to `soundspace`. It would be great that `soundspace` supports local sources.
