### ISSUE TITLE
Asking for new YouTube Streams

### ISSUE THREAD

**Issue by useronegit** [andrewmcgivery/obsidian-soundscapes#31]
All from Lofi Girl

peaceful piano radio 🎹 - music to focus/study to
https://www.youtube.com/watch?v=nWjC1RnLYbM

synthwave radio 🌌 - beats to chill/game to 
https://www.youtube.com/watch?v=4xDzrJKXOOY

**Comment by andrewmcgivery** [comment]
These have been added in version 1.4.0. :)
