### ISSUE TITLE
Thank you, It's nice to be able to use Obsidian while listening to music.

### ISSUE THREAD

**Issue by OPEN1004MIND** [andrewmcgivery/obsidian-soundscapes#4]
It's nice to be able to use Obsidian while listening to music.
I can listen to MP3s separately, but it's nice to be able to do it in one program.

The only thing I wish is that you could register a specific address for a YouTube channel and have the ability to register and select it in the settings.

**Comment by andrewmcgivery** [comment]
That is absolutely on my list as a fast follower once it is accepted into the community plugins officially! Stay tuned!

**Comment by andrewmcgivery** [comment]
Custom Soundscapes are now available in version 1.1.0!

**Comment by OPEN1004MIND** [comment]
Thank you well done. 
I've tested your upgrade and it works fine.

**Comment by OPEN1004MIND** [comment]
Thank you well done.
I've tested your upgrade and it works fine.
