### ISSUE TITLE
Contribution and Feedback 

### ISSUE THREAD

**Issue by Snifer** [andrewmcgivery/obsidian-soundscapes#6]
I wanted to express my gratitude for your excellent work on this plug-in. 

I have made a small modification to the main.js file that allows users to add any YouTube video ID for playback. Though my JavaScript knowledge is limited, I hope this contribution proves helpful in some way.

I have pushed the modification to the main.js file to my GitHub repository. You can find the reference to this alteration here. In the future, I aspire to contribute more substantially with TypeScript code, once I enhance my skills in that area.

 I look forward to potentially pull request more significantly in the future.

Best regards,
Snifer
https://github.com/Snifer/Obsidian-Plugin-Tweaks/tree/main?tab=readme-ov-file#soundscapes

**Comment by andrewmcgivery** [comment]
Hi there :)

Appreciate the idea and effort!

I've actually got "custom soundscapes" coming soon which will allow for multiple, multi-track soundscapes.

With that in mind, I'm going to close this issue.

Thanks!
